[package]
name = "indradb"
version = "0.13.0"
authors = ["Yusuf Simonson <simonson@gmail.com>"]
description = "A graph database server"
homepage = "https://indradb.github.io"
repository = "https://github.com/indradb/indradb"
keywords = ["graph", "database"]
categories = ["database", "database-implementations"]
license = "MPL-2.0"

[badges]
travis-ci = { repository = "indradb/indradb", branch = "master" }

[features]
test-suite = ["indradb-lib/test-suite"]
bench-suite = ["indradb-lib/bench-suite"]

[[bin]]
name = "indradb-admin"
path = "src/admin/main.rs"

[[bin]]
name = "indradb-server"
path = "src/server/main.rs"

[lib]
name = "common"
path = "src/common/lib.rs"

[dependencies]
actix = "0.5"
actix-web = "^0.6"
bytes = "0.4.7"
env_logger = "0.5"
futures = "0.1"
serde = "^1.0.27"
serde_json = "^1.0.9"
serde_derive = "^1.0.27"
libc = "0.2.26"
rand = "~0.4.2"
regex = "~0.2.5"
lazy_static = "^1.0.0"
iron = "0.6.0"
hyper = "0.11.16"
clap = "^2.29.4"
rlua = "0.13.0"
num_cpus = "^1.8.0"
juniper = "0.9.2"
juniper_codegen = "0.9.2"
ordermap = "0.2.13"
crossbeam-channel = "0.1.2"
chrono = { version = "0.4.0", features = ["serde"] }
uuid = { version = "0.5.1", features = ["serde", "v4"] }

[dependencies.indradb-lib]
path = "../lib"
version = "0.13.0"
features = ["postgres-datastore", "rocksdb-datastore"]
