[package]
name = "indradb"
version = "0.15.0"
authors = ["Yusuf Simonson <simonson@gmail.com>"]
description = "A graph database server"
homepage = "https://indradb.github.io"
repository = "https://github.com/indradb/indradb"
keywords = ["graph", "database"]
categories = ["database", "database-implementations"]
license = "MPL-2.0"
build = "build.rs"

[badges]
travis-ci = { repository = "indradb/indradb", branch = "master" }

[features]
bench-suite = ["indradb-lib/bench-suite"]
test-suite = ["indradb-lib/test-suite"]

[[bin]]
name = "indradb"
path = "src/server/main.rs"

[lib]
name = "common"
path = "src/common/lib.rs"

[dependencies]
error-chain = "~0.11.0"
serde = "^1.0.27"
serde_json = "^1.0.9"
serde_derive = "^1.0.27"
libc = "0.2.26"
rand = "~0.4.2"
regex = "~0.2.5"
clap = "2.29.4"
grpcio = "0.2.1"
lazy_static = "1.0.0"
capnp = "0.8.17"
capnp-rpc = "0.8.3"
futures = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"
futures-cpupool = "0.1"
chrono = { version = "0.4.0", features = ["serde"] }
uuid = { version = "0.5.1", features = ["serde", "v4"] }

[dependencies.indradb-lib]
path = "../lib"
version = "0.15.0"
features = ["test-suite", "rocksdb-datastore"]

[build-dependencies]
capnpc = "0.8.9"
