[package]
name = "indradb"
version = "0.17.0"
authors = ["Yusuf Simonson <simonson@gmail.com>"]
description = "A graph database server"
homepage = "https://indradb.github.io"
repository = "https://github.com/indradb/indradb"
keywords = ["graph", "database"]
categories = ["database", "database-implementations"]
license = "MPL-2.0"
build = "build.rs"

[badges]
travis-ci = { repository = "indradb/indradb", branch = "master" }

[features]
bench-suite = ["indradb-lib/bench-suite"]
test-suite = ["indradb-lib/test-suite"]

[[bin]]
name = "indradb"
path = "src/server/main.rs"

[lib]
name = "common"
path = "src/common/lib.rs"

[dependencies]
error-chain = "~0.12.0"
serde = "^1.0.79"
serde_json = "^1.0.31"
serde_derive = "^1.0.79"
libc = "0.2.43"
rand = "~0.5.5"
regex = "^1.0.5"
clap = "^2.32.0"
lazy_static = "^1.1.0"
capnp = "0.9.1"
capnp-rpc = "0.9.0"
futures = "0.1.25"
tokio-core = "0.1.17"
tokio-io = "0.1.10"
futures-cpupool = "0.1.8"
num_cpus = "1.8.0"
chrono = { version = "0.4.6", features = ["serde"] }
uuid = { version = "~0.7.1", features = ["serde", "v4"] }

[dependencies.indradb-lib]
path = "../lib"
version = "0.17.0"
features = ["test-suite", "rocksdb-datastore"]

[build-dependencies]
capnpc = "0.9.0"