[package]
name = "indradb"
version = "0.22.0"
authors = ["Yusuf Simonson <simonson@gmail.com>"]
description = "A graph database server"
homepage = "https://indradb.github.io"
repository = "https://github.com/indradb/indradb"
keywords = ["graph", "database"]
categories = ["database", "database-implementations"]
license = "MPL-2.0"
build = "build.rs"
edition = "2018"

[badges]
travis-ci = { repository = "indradb/indradb", branch = "master" }

[features]
bench-suite = ["indradb-lib/bench-suite"]
test-suite = ["indradb-lib/test-suite"]

[[bin]]
name = "indradb"
path = "src/server/main.rs"

[lib]
name = "common"
path = "src/common/lib.rs"

[dependencies]
failure = "0.1.6"
serde_json = "^1.0.44"
lazy_static = "^1.4.0"
uuid = "0.8.1"
capnp = "0.9.4"
capnp-rpc = "0.9.0"
futures = "0.1.25"
tokio-core = "0.1.17"
tokio-io = "0.1.11"
futures-cpupool = "0.1.8"
num_cpus = "1.11.1"
chrono = "0.4.10"

[dependencies.indradb-lib]
path = "../lib"
version = "0.22.0"
features = ["test-suite", "rocksdb-datastore"]

[build-dependencies]
capnpc = "0.9.3"
