[package]
name = "indradb"
version = "0.15.0"
authors = ["Yusuf Simonson <simonson@gmail.com>"]
description = "A graph database server"
homepage = "https://indradb.github.io"
repository = "https://github.com/indradb/indradb"
keywords = ["graph", "database"]
categories = ["database", "database-implementations"]
license = "MPL-2.0"
build = "build.rs"

[badges]
travis-ci = { repository = "indradb/indradb", branch = "master" }

[features]
bench-suite = ["indradb-lib/bench-suite"]

[[bin]]
name = "indradb"
path = "src/server/main.rs"

[lib]
name = "common"
path = "src/common/lib.rs"

[dependencies]
error-chain = "~0.12.0"
serde = "^1.0.79"
serde_json = "^1.0.31"
serde_derive = "^1.0.79"
libc = "0.2.43"
rand = "~0.5.5"
regex = "^1.0.5"
clap = "^2.32.0"
chan-signal = "0.3.1"
grpcio = "0.2.1"
protobuf = "1.4.4"
futures = "0.1.18"
lazy_static = "^1.1.0"
chrono = { version = "0.4.6", features = ["serde"] }
uuid = { version = "~0.7.1", features = ["serde", "v4"] }

[dependencies.indradb-lib]
path = "../lib"
version = "0.15.0"
features = ["rocksdb-datastore"]

[build-dependencies]
# Currently relying on an unpublished patch for this to workin TravisCI
protoc-grpcio = { git = "https://github.com/mtp401/protoc-grpcio" }
