dist: trusty
language: rust
services: docker
sudo: required

addons:
  postgresql: "9.5"
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - libiberty-dev

matrix:
  include:
    # Rust stable
    - rust: stable
      env:
      - TARGET=x86_64-unknown-linux-gnu
      - PKG_CONFIG_PATH=/usr/lib/pkgconfig:$PKG_CONFIG_PATH
      - PG_USER=postgres
      - TEST_POSTGRES_URL="postgres://$PG_USER@localhost:5432/indradb_test"
      - PATH=$HOME/.local/bin:$HOME/kcov-master/build:$PATH
    - os: osx
      rust: stable
      env:
      - TARGET=x86_64-apple-darwin
      - PG_USER=travis
      - TEST_POSTGRES_URL="postgres://$PG_USER@localhost:5432/indradb_test"
      - PATH=$HOME/Library/Python/2.7/bin:$HOME/kcov-master/build:$PATH

    # Rust beta
    - rust: beta
      env:
      - TARGET=x86_64-unknown-linux-gnu
      - PKG_CONFIG_PATH=/usr/lib/pkgconfig:$PKG_CONFIG_PATH
      - PG_USER=postgres
      - TEST_POSTGRES_URL="postgres://$PG_USER@localhost:5432/indradb_test"
      - PATH=$HOME/.local/bin:$HOME/kcov-master/build:$PATH

    # Rust nightly
    - rust: nightly
      env:
      - TARGET=x86_64-unknown-linux-gnu
      - PKG_CONFIG_PATH=/usr/lib/pkgconfig:$PKG_CONFIG_PATH
      - PG_USER=postgres
      - TEST_POSTGRES_URL="postgres://$PG_USER@localhost:5432/indradb_test"
      - PATH=$HOME/.local/bin:$HOME/kcov-master/build:$PATH
      - RUSTFLAGS="-C link-dead-code"

  allow_failures:
    # Rust nightly
    - rust: nightly
      env:
      - TARGET=x86_64-unknown-linux-gnu
      - PKG_CONFIG_PATH=/usr/lib/pkgconfig:$PKG_CONFIG_PATH
      - PG_USER=postgres
      - TEST_POSTGRES_URL="postgres://$PG_USER@localhost:5432/indradb_test"
      - PATH=$HOME/.local/bin:$HOME/kcov-master/build:$PATH
      - RUSTFLAGS="-C link-dead-code"

env:
  global:
    - TEST_RDB_DIRECTORY=/tmp/indradb
    - RUST_BACKTRACE=1
    - SECRET=QkrDxgVJCT
    - INDRADB_SCRIPT_ROOT=~/build/indradb/indradb/bin/test_scripts

install: ./ci/install.sh

before_script: ./ci/before_script.sh
script: ./ci/test.py

before_deploy: ./ci/before_deploy.sh

deploy:
  api_key:
    secure: "SJWoEbIpr35KQUnJHle5JQ451e7Ods7XbHMKIoUMt28jZPCz+pcC1rx4RlIzt19F0hCf6LNIRjwy8T86PkPORuyKrXiihefxg3dJWh52bElHT7pml9VMegKRO5/SVysZNqG65qcm6JkYwZTNn2rqk6jbcIhs0mXQA10c+IwThHmS5+O97pqfJfinKVaVa2+uGOVZALy8laMB2YVUkD5wFwSN+fjJhTIRB4wH54ufMlYD0IQ/3K5/EmJ4ddu1hvLQ9mKRSew5lOY5MgVk2csZkGem/bFa0FqBmZSOuCmliotopmITUvufkTSKPjPmC90rKF7jFW9uqbOaRMsUiFnzoRuDfLGDOKz26QK7K2A0ClWo5ThoXt1V142OMSHmr6OZysWhKf+wlwqht9YvkWrjmEwP333n0rrbJeosloKeSTZDS7j2VIfRCn3H2J5AUJuix92MGeJFzDnKDFzZfOlsUgvULXiHcgpXrSKmkhMFn5noN4DD+xZEep/XaQTKEVIZi05HJqX9eDnVMeip6Unya4dx44rTzGS0y8bko69hvkh9i8iG33x1VkVfUSNUOERVL1Tmns2cKQFWq+yN2i2zRPVm6vLtBZSGhacYSVpW2CbxpdsNyZv83VCD99LI2Eomy1QeWufbrBHxM650V25PSDXS6HiEHEzwpY6yhSsKciw="
  file_glob: true
  file: indradb-$TRAVIS_TAG-$TARGET.*
  on:
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
  provider: releases
  skip_cleanup: true

cache:
  directories:
  - bin/target
  - lib/target
  - $HOME/.cargo
  - $TRAVIS_BUILD_DIR/target
  - /usr/local/bin/kcov
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

notifications:
  email:
on_success: never
