dist: trusty
language: rust
services: docker
sudo: required

addons:
  postgresql: "9.5"
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - libiberty-dev

matrix:
  include:
    # Rust stable
    - rust: stable
      env:
      - TARGET=x86_64-unknown-linux-gnu
      - PKG_CONFIG_PATH=/usr/lib/pkgconfig:$PKG_CONFIG_PATH
      - PG_USER=postgres
      - TEST_POSTGRES_URL="postgres://$PG_USER@localhost:5432/indradb_test"
      - PATH=$HOME/.local/bin:$HOME/kcov-master/build:$PATH
    - os: osx
      rust: stable
      env:
      - TARGET=x86_64-apple-darwin
      - PG_USER=travis
      - TEST_POSTGRES_URL="postgres://$PG_USER@localhost:5432/indradb_test"
      - PATH=$HOME/Library/Python/2.7/bin:$HOME/kcov-master/build:$PATH

    # Rust beta
    - rust: beta
      env:
      - TARGET=x86_64-unknown-linux-gnu
      - PKG_CONFIG_PATH=/usr/lib/pkgconfig:$PKG_CONFIG_PATH
      - PG_USER=postgres
      - TEST_POSTGRES_URL="postgres://$PG_USER@localhost:5432/indradb_test"
      - PATH=$HOME/.local/bin:$HOME/kcov-master/build:$PATH

    # Rust nightly
    - rust: nightly
      env:
      - TARGET=x86_64-unknown-linux-gnu
      - PKG_CONFIG_PATH=/usr/lib/pkgconfig:$PKG_CONFIG_PATH
      - PG_USER=postgres
      - TEST_POSTGRES_URL="postgres://$PG_USER@localhost:5432/indradb_test"
      - PATH=$HOME/.local/bin:$HOME/kcov-master/build:$PATH
      - RUSTFLAGS="-C link-dead-code"

  allow_failures:
    # Rust nightly
    - rust: nightly
      env:
      - TARGET=x86_64-unknown-linux-gnu
      - PKG_CONFIG_PATH=/usr/lib/pkgconfig:$PKG_CONFIG_PATH
      - PG_USER=postgres
      - TEST_POSTGRES_URL="postgres://$PG_USER@localhost:5432/indradb_test"
      - PATH=$HOME/.local/bin:$HOME/kcov-master/build:$PATH
      - RUSTFLAGS="-C link-dead-code"

env:
  global:
    - TEST_RDB_DIRECTORY=/tmp/indradb
    - RUST_BACKTRACE=1
    - SECRET=QkrDxgVJCT
    - INDRADB_SCRIPT_ROOT=~/build/indradb/indradb/bin/test_scripts

install: ./ci/install.sh

before_script: ./ci/before_script.sh
script: ./ci/test.py

before_deploy: ./ci/before_deploy.sh

deploy:
  api_key:
    secure: "Ds2fcnNaue7lBr8ABROPe4eNwCY1s28a3amoydPgA7oZUu+89mcMhX/Jp9k0RtE/TQn0gtHsFzJPLCsucvf3MHLvsHa5Usd8LSfcG3JlztIM2QnfoEtZTUdb3d6JsT5GUlUJNhrNgH9SL0oIkK1q8Lzmg70URCgZjP3TrwpuX3CEkDDNc7khOw9W+ojZwH1JPJWE9rljIMiO8/ISz5fd62s6csIWI8PEm1iH48AxZqd3GmCzqrdUaqJqboHFoA0YyvJpMzEKG+/ArL3HleBI80xIesOl1MaPtXYHrm8Dkf2DNi03ReTbTezUN84rzvEoTV4GtXd1z6ajSZNkpSPIYG6l6hjE/5AzB2EcDVdU17AirJ3u950FG5+mn0w3nAZf67SH4si/4EvWAPvneXO+NZjUS8jyQ/uBXjp5r08z2DCaThKTR2v4K9vJMtF6puV9hYLmjhJepBDuT+WCXPcuKhd1ICRPoTAo6DLA6Do8NvwXu1QSDmyObTb8ZdqTnMIisFy332c6ZxYTCTa2ec1Zq4oI1jlBEs0kE7X7oqoGjF/Qn8kpZZ9ak0YwDZzdc89yisE1HsbUZFnqT1k6V3r6teyv0U1iXZGvw63PwFQ+J5U0jFR1O5uZdCUwd9+ChiAC4hg/47OBjghDOvDGMp3KsdTfM2obWicx0YSogvVTpBs="
  file_glob: true
  file: indradb-$TRAVIS_TAG-$TARGET.*
  on:
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
  provider: releases
  skip_cleanup: true

cache:
  directories:
  - bin/target
  - lib/target
  - $HOME/.cargo
  - $TRAVIS_BUILD_DIR/target
  - /usr/local/bin/kcov
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

notifications:
  email:
on_success: never
