language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
dist: trusty
addons:
  postgresql: "9.5"
before_script:
  - psql -c 'create database braid_test;' -U postgres
script:
  - ./test.sh
