[package]
name = "rust-nutrino-lib"
version = "0.1.0"
authors = ["Yusuf Simonson <simonson@gmail.com>"]

[lib]
name = "nutrino"
path = "src/lib.rs"

[features]
default = ["postgres-datastore", "rocksdb-datastore"]
postgres-datastore = ["postgres", "r2d2", "r2d2_postgres", "num_cpus"]
rocksdb-datastore = ["rocksdb", "librocksdb-sys", "bincode", "lazy_static", "byteorder"]

[dependencies]
rust-crypto = "~0.2.36"
chrono = "~0.2.25"
serde = "~0.8.13"
serde_json = "~0.8.3"
serde_derive = "~0.8.19"
libc = "~0.2.18"
rand = "~0.3.15"
regex = "~0.1.80"

# Postgres dependencies
r2d2 = { version = "~0.7.1", optional = true }
r2d2_postgres = { version = "~0.11.1", optional = true }
num_cpus = { version = "^1.2.0", optional = true }

# Rocksdb dependencies
rocksdb = { version = "~0.5.0", optional = true }
librocksdb-sys = { version = "~0.4.0", optional = true }
lazy_static = { version = "~0.2.2", optional = true }
byteorder = { version = "~0.5.3", optional = true }

[dev-dependencies]
stainless = "~0.1.10"

[dependencies.bincode]
version = "~0.6.0"
optional = true
features = ["serde"]

[dependencies.uuid]
version = "~0.3.1"
features = ["serde", "v4"]

[dependencies.postgres]
version = "~0.13.3"
features = ["with-serde_json", "with-chrono", "with-uuid"]
optional = true
