[package]
name = "rust-nutrino-lib"
version = "0.1.0"
authors = ["Yusuf Simonson <simonson@gmail.com>"]

[lib]
name = "nutrino"
path = "src/lib.rs"

[features]
default = ["postgres-datastore"]
postgres-datastore = ["postgres", "r2d2", "r2d2_postgres", "num_cpus"]

[dependencies]
rust-crypto = "0.2.35"
chrono = "0.2.20"
serde = "0.8.8"
serde_macros = "0.8.8"
libc = "0.2.11"

# Postgres dependencies
r2d2 = { version = "0.7.0", optional = true }
r2d2_postgres = { version = "0.10.1", optional = true }
num_cpus = { version = "0.2.11", optional = true }

[dependencies.serde_json]
git = "https://github.com/serde-rs/json"

[dependencies.postgres]
version = "0.11.3"
features = ["uuid", "serde_json", "chrono"]
optional = true

[dev-dependencies]
rand = "0.3.14"
